name: Deploy to NCP

on:
  push:
    branches: [ "main" ]

jobs:
  ci: 
    runs-on: ubuntu-latest   # ❗ 필수

    steps: 
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
      - run: npm run test

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/chat-live/livechatWSS

            git pull origin main

            npm install            
            npm run lint
            
            pm2 reload app || pm2 start web.js --name app